apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmc-delal-uploads
  labels:
    app: cmc-delal-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi