apiVersion: v1
kind: Service
metadata:
  name: cmc-delal-backend
  labels:
    app: cmc-delal-backend
spec:
  type: ClusterIP
  selector:
    # MUST match the pod labels in deployment.yaml
    app: cmc-delal-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP